### ISSUE TITLE
Add a Build.last_commit validation.

### ISSUE THREAD

**Issue by richardkmichael** [richardkmichael/buy-my-beer#15]
app/models/build.rb

This might assume we're always using Git, e.g. if we validate for SHA1.

What does SVN produce?  Should we care?

**Comment by franckverrot** [comment]
A Git SHA-1 is your unique identifier for a Git repo. You can get an unique identifier out of a SVN repo too (it's revision number). You can subclass the Build model in this case.

**Comment by richardkmichael** [comment]
Yeah, I know SVN from the old days.  I guess I could sub-class, then put validations on the sub-classes.

(Which raises an interesting idea, that different models can validate string parameters in different ways, but store them in the same DB field.  So some kind of stored-procedure or constraint on the field in the DB directly wouldn't work.  Not a problem per se, just observing.)

**Comment by franckverrot** [comment]
You can get serious with DB constraints but it's damn hard to keep them in
sync

[project table, using STI with sti_column = type]
ADD CONSTRAINT check_for_stuff CHECK
((type = "git" AND name ILIKE 'somepattern') OR (type = "svn" AND name ILIKE
'someotherpatternforsvn'))

On Mon, Sep 5, 2011 at 1:04 PM, richardkmichael <
reply@reply.github.com>wrote:

> Yeah, I know SVN from the old days.  I guess I could sub-class, then put
> validations on the sub-classes.
> 
> (Which raises an interesting idea, that different models can validate
> string parameters in different ways, but store them in the same DB field.
>  So some kind of stored-procedure or constraint on the field in the DB
> directly wouldn't work.  Not a problem per se, just observing.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/richardkmichael/buy-my-beer/issues/15#issuecomment-1998304

## 

Franck Verrot
https://github.com/cesario
https://twitter.com/cesariogw

**Comment by richardkmichael** [comment]
I'll only support Git for now, so validate the format of the SHA-1.  I'll add subversion project support later, if there's enough interest.

Closed by this SHA: ff898df83e1e37502b68f09cfce5787b09ed0ea0
